#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Test-MockModule
Version  : 0.176.0
Release  : 23
URL      : https://cpan.metacpan.org/authors/id/G/GF/GFRANKS/Test-MockModule-v0.176.0.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/G/GF/GFRANKS/Test-MockModule-v0.176.0.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libt/libtest-mockmodule-perl/libtest-mockmodule-perl_0.170.0-1.debian.tar.xz
Summary  : 'Override subroutines in a module for unit testing'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Test-MockModule-license = %{version}-%{release}
Requires: perl-Test-MockModule-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : perl(Test::Warnings)

%description
# Test::MockModule - mock subroutines in a module
See the LICENSE section in `lib/Test/MockModule.pm` for usage and
distribution rights.

%package dev
Summary: dev components for the perl-Test-MockModule package.
Group: Development
Provides: perl-Test-MockModule-devel = %{version}-%{release}
Requires: perl-Test-MockModule = %{version}-%{release}

%description dev
dev components for the perl-Test-MockModule package.


%package license
Summary: license components for the perl-Test-MockModule package.
Group: Default

%description license
license components for the perl-Test-MockModule package.


%package perl
Summary: perl components for the perl-Test-MockModule package.
Group: Default
Requires: perl-Test-MockModule = %{version}-%{release}

%description perl
perl components for the perl-Test-MockModule package.


%prep
%setup -q -n Test-MockModule-v0.176.0
cd %{_builddir}
tar xf %{_sourcedir}/libtest-mockmodule-perl_0.170.0-1.debian.tar.xz
cd %{_builddir}/Test-MockModule-v0.176.0
mkdir -p deblicense/
cp -r %{_builddir}/debian/* %{_builddir}/Test-MockModule-v0.176.0/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Test-MockModule
cp %{_builddir}/debian/copyright %{buildroot}/usr/share/package-licenses/perl-Test-MockModule/df4957f7d747e74e0bfa20d6b99a2fac98bb9753
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Test::MockModule.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Test-MockModule/df4957f7d747e74e0bfa20d6b99a2fac98bb9753

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.30.3/Test/MockModule.pm
